#include "Zenith.h"

#ifdef ZENITH_TOOLS

#include "Zenith_ComponentRegistry.h"

//==============================================================================
// Component Registry Auto-Registration
//==============================================================================
// Components automatically register with the editor the first time their
// TypeID is generated by Zenith_Scene::TypeIDGenerator::GetTypeID<T>().
//
// The TypeIDGenerator checks if a type has a static RegisterWithEditor()
// function using C++20 requires expressions, and calls it automatically.
//
// This ensures:
// 1. Zero-cost abstraction - registration only happens when component is used
// 2. No manual registration list to maintain
// 3. Impossible to forget to register (enforced by concepts)
// 4. Each component registers exactly once (static local in TypeIDGenerator)
// 5. No duplicate registrations from multiple translation units
//==============================================================================
// No manual initialization needed - components auto-register on first use!

#endif // ZENITH_TOOLS
