#include "Zenith.h"
#include "Core/Memory/Zenith_MemoryManagement_Disabled.h"

#include "Flux/Slang/Flux_CodeGenerator.h"
#include "Flux/Slang/Flux_SlangCompiler.h"
#include "Flux/Slang/Flux_ShaderRegistry.h"

#include <cstdio>
#include <fstream>
#include <map>
#include <string>
#include <vector>

namespace
{
	constexpr const char* kBanner =
		"// =====================================================================\n"
		"// AUTO-GENERATED — DO NOT EDIT\n"
		"//\n"
		"// Regenerated by FluxCompiler from Slang reflection. Hand edits will\n"
		"// be overwritten on the next FluxCompiler run. Source of truth is the\n"
		"// shader registry plus the linked Slang reflection per program.\n"
		"// =====================================================================\n";

	bool WriteIfChanged(const std::string& strPath, const std::string& strContent)
	{
		// Idempotent write: only touch the file if content differs. Keeps build
		// timestamps stable when nothing changed and lets CI's
		// regenerate-and-diff freshness check produce empty diffs on no-op.
		std::ifstream xExisting(strPath, std::ios::binary);
		if (xExisting.good())
		{
			std::string strOld((std::istreambuf_iterator<char>(xExisting)),
								std::istreambuf_iterator<char>());
			if (strOld == strContent) return true;
		}
		xExisting.close();

		std::ofstream xOut(strPath, std::ios::binary | std::ios::trunc);
		if (!xOut.is_open())
		{
			printf("CODEGEN: failed to open '%s' for write\n", strPath.c_str());
			return false;
		}
		xOut.write(strContent.data(), static_cast<std::streamsize>(strContent.size()));
		return xOut.good();
	}

	std::string SanitizeIdentifier(const std::string& strIn)
	{
		std::string strOut;
		strOut.reserve(strIn.size());
		for (char c : strIn)
		{
			if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_')
				strOut += c;
			else
				strOut += '_';
		}
		if (!strOut.empty() && strOut[0] >= '0' && strOut[0] <= '9') strOut.insert(strOut.begin(), '_');
		return strOut;
	}

	const char* ResourceKindName(FluxResourceKind eKind)
	{
		switch (eKind)
		{
		case FLUX_RESOURCE_KIND_CONSTANT_BUFFER:        return "ConstantBuffer";
		case FLUX_RESOURCE_KIND_STRUCTURED_BUFFER:      return "StructuredBuffer";
		case FLUX_RESOURCE_KIND_RW_STRUCTURED_BUFFER:   return "RWStructuredBuffer";
		case FLUX_RESOURCE_KIND_BYTE_ADDRESS_BUFFER:    return "ByteAddressBuffer";
		case FLUX_RESOURCE_KIND_RW_BYTE_ADDRESS_BUFFER: return "RWByteAddressBuffer";
		case FLUX_RESOURCE_KIND_TEXTURE:                return "Texture";
		case FLUX_RESOURCE_KIND_RW_TEXTURE:             return "RWTexture";
		case FLUX_RESOURCE_KIND_SAMPLER:                return "Sampler";
		case FLUX_RESOURCE_KIND_COMBINED_TEXTURE_SAMPLER: return "CombinedTextureSampler";
		case FLUX_RESOURCE_KIND_ACCELERATION_STRUCTURE: return "AccelerationStructure";
		case FLUX_RESOURCE_KIND_UNBOUNDED_TEXTURE_ARRAY: return "UnboundedTextureArray";
		case FLUX_RESOURCE_KIND_PARAMETER_BLOCK:        return "ParameterBlock";
		default: return "Unknown";
		}
	}

	// Engine Hungarian prefix for a generated member, given its Slang type.
	// Scalar prefixes (`f`, `u`, `i`, `b`) follow the C++ conventions; vec /
	// mat / struct types use `x`. Caller still prepends `m_` (member) and
	// flips to `a` for arrays.
	struct CppMapping
	{
		const char* m_szSlang     = nullptr;
		const char* m_szCpp       = nullptr;
		char        m_chHungarian = 'x';
	};

	// Map a Slang/HLSL type name (as returned by reflection) to a C++ type
	// name and Hungarian prefix suitable for emitting in a generated CB
	// struct. Returns nullptr when the type is unknown — caller falls back
	// to a byte buffer of the reflected size. Coverage is the scalar /
	// vector / matrix types Zenith shaders actually use today; extend this
	// table as new types appear.
	const CppMapping* MapSlangTypeToCpp(const std::string& strSlangType)
	{
		static const CppMapping s_axMappings[] = {
			// scalars
			{ "float",     "float",        'f' },
			{ "uint",      "unsigned int", 'u' },
			{ "int",       "int",          'i' },
			{ "bool",      "unsigned int", 'b' }, // bool in CB is 4 bytes, std140
			// vectors (Slang/HLSL)
			{ "float2",    "glm::vec2",    'x' },
			{ "float3",    "glm::vec3",    'x' },
			{ "float4",    "glm::vec4",    'x' },
			{ "uint2",     "glm::uvec2",   'x' },
			{ "uint3",     "glm::uvec3",   'x' },
			{ "uint4",     "glm::uvec4",   'x' },
			{ "int2",      "glm::ivec2",   'x' },
			{ "int3",      "glm::ivec3",   'x' },
			{ "int4",      "glm::ivec4",   'x' },
			// vectors (GLSL aliases — Slang reflection may surface either
			// form depending on source language; cover both for safety)
			{ "vec2",      "glm::vec2",    'x' },
			{ "vec3",      "glm::vec3",    'x' },
			{ "vec4",      "glm::vec4",    'x' },
			{ "uvec2",     "glm::uvec2",   'x' },
			{ "uvec3",     "glm::uvec3",   'x' },
			{ "uvec4",     "glm::uvec4",   'x' },
			{ "ivec2",     "glm::ivec2",   'x' },
			{ "ivec3",     "glm::ivec3",   'x' },
			{ "ivec4",     "glm::ivec4",   'x' },
			// matrices
			{ "float3x3",  "glm::mat3",    'x' },
			{ "float4x4",  "glm::mat4",    'x' },
			{ "mat3",      "glm::mat3",    'x' },
			{ "mat4",      "glm::mat4",    'x' },
		};
		for (const CppMapping& xM : s_axMappings)
		{
			if (strSlangType == xM.m_szSlang) return &xM;
		}
		return nullptr;
	}
}

std::string Flux_CodeGenerator::BuildProgramEnumContent()
{
	std::string strContent;
	strContent += kBanner;
	strContent += "#pragma once\n\n";
	strContent += "enum class FluxShaderProgram : unsigned int\n{\n";

	const u_int uCount = Flux_ShaderRegistry::GetProgramCount();
	for (u_int u = 0; u < uCount; u++)
	{
		const Flux_ShaderRegistryEntry& xEntry = Flux_ShaderRegistry::GetProgramByIndex(u);
		char szLine[256];
		snprintf(szLine, sizeof(szLine), "\t%s = %u,\n", xEntry.m_szName, u);
		strContent += szLine;
	}
	strContent += "\n\tCOUNT\n};\n";
	return strContent;
}

bool Flux_CodeGenerator::WriteProgramEnumHeader(const char* szOutputDir)
{
	std::string strContent = BuildProgramEnumContent();
	std::string strPath = std::string(szOutputDir) + "FluxShaderProgram.h";
	return WriteIfChanged(strPath, strContent);
}

std::string Flux_CodeGenerator::BuildSubsystemHeaderContent(const char* szSubsystem,
															 const ProgramReflection* axPrograms,
															 u_int uProgramCount)
{
	std::string strSubsystem = szSubsystem ? szSubsystem : "Misc";

	std::string strContent;
	strContent += kBanner;
	strContent += "#pragma once\n\n";
	strContent += "#include \"Flux/Slang/Flux_SlangCompiler.h\"\n";
	strContent += "#include \"glm/glm.hpp\"\n";
	strContent += "#include <cstddef>\n\n";
	strContent += "namespace Flux_Generated_" + SanitizeIdentifier(strSubsystem) + "\n{\n";

	// Per-program section: emit binding-path constants for every reflected
	// resource, plus a CB struct skeleton when the program has CB or PB
	// resources. Field-level offset asserts only emit when reflection
	// captured the inner field list (CB and PB only).
	for (u_int u = 0; u < uProgramCount; u++)
	{
		const ProgramReflection& xPR = axPrograms[u];
		if (!xPR.m_pxReflection) continue;
		const Flux_ShaderRegistryEntry& xEntry = Flux_ShaderRegistry::GetProgram(xPR.m_eId);

		std::string strProgIdent = SanitizeIdentifier(xEntry.m_szName);
		strContent += "\t// ----- " + std::string(xEntry.m_szName) + " (" + xEntry.m_szModuleName + ") -----\n";
		strContent += "\tnamespace " + strProgIdent + "\n\t{\n";

		const Zenith_Vector<Flux_ReflectedBinding>& axBindings = xPR.m_pxReflection->GetBindings();
		for (u_int b = 0; b < axBindings.GetSize(); b++)
		{
			const Flux_ReflectedBinding& xBinding = axBindings.Get(b);
			if (xBinding.m_strName.empty()) continue;
			std::string strBindIdent = SanitizeIdentifier(xBinding.m_strName);
			char szLine[512];
			snprintf(szLine, sizeof(szLine),
					 "\t\tinline constexpr const char* k%s_Name = \"%s\";\n"
					 "\t\tinline constexpr unsigned int k%s_Set = %u;\n"
					 "\t\tinline constexpr unsigned int k%s_Binding = %u;\n"
					 "\t\tinline constexpr unsigned int k%s_DescriptorCount = %u;\n"
					 "\t\t// kind: %s\n",
					 strBindIdent.c_str(), xBinding.m_strName.c_str(),
					 strBindIdent.c_str(), xBinding.m_uSet,
					 strBindIdent.c_str(), xBinding.m_uBinding,
					 strBindIdent.c_str(), xBinding.m_uDescriptorCount,
					 ResourceKindName(xBinding.m_eResourceKind));
			strContent += szLine;

			// CB / PB struct emission. Each reflected scalar/vector/matrix
			// field maps to a typed C++ member (with offsetof + sizeof
			// static_asserts); fields whose Slang type isn't in the mapping
			// table fall back to a sized byte buffer so the struct still has
			// the right footprint and the size_assert still catches drift.
			//
			// std140 layout pads vec3 to 16-byte boundaries and pads the whole
			// CB up to the next 16 bytes — the reflected offsets capture that,
			// so the emission walks `uRunningOffset` and inserts an explicit
			// `pad_<offset>` byte array whenever the next field's reflected
			// offset is past the running cursor (or the struct's total size
			// exceeds the sum of fields). Without this, sizeof asserts fail
			// for any CB whose layout has interior or trailing pad.
			if ((xBinding.m_eResourceKind == FLUX_RESOURCE_KIND_CONSTANT_BUFFER ||
				 xBinding.m_eResourceKind == FLUX_RESOURCE_KIND_PARAMETER_BLOCK) &&
				xBinding.m_axFields.GetSize() > 0)
			{
				strContent += "\t\tstruct " + strBindIdent + "_CB\n\t\t{\n";
				u_int uRunningOffset = 0;
				for (u_int f = 0; f < xBinding.m_axFields.GetSize(); f++)
				{
					const Flux_ReflectedField& xField = xBinding.m_axFields.Get(f);
					std::string strFieldIdent = SanitizeIdentifier(xField.m_strName);
					const CppMapping* pxMap = MapSlangTypeToCpp(xField.m_strTypeName);

					// Insert padding bytes if the reflected offset is ahead
					// of where we've emitted to. The pad name carries the
					// offset so identical offsets across CBs don't collide.
					if (xField.m_uOffset > uRunningOffset)
					{
						const u_int uPad = xField.m_uOffset - uRunningOffset;
						char szPad[160];
						snprintf(szPad, sizeof(szPad),
								 "\t\t\tunsigned char m_aPad_%u[%u];\n",
								 uRunningOffset, uPad);
						strContent += szPad;
						uRunningOffset = xField.m_uOffset;
					}

					char szField[512];
					u_int uFieldFootprint = 0;
					if (pxMap && xField.m_uArrayCount <= 1)
					{
						// Scalar / vector / matrix field with engine Hungarian prefix.
						snprintf(szField, sizeof(szField),
								 "\t\t\t%s m_%c%s; // slang=%s offset=%u\n",
								 pxMap->m_szCpp,
								 pxMap->m_chHungarian,
								 strFieldIdent.c_str(),
								 xField.m_strTypeName.c_str(),
								 xField.m_uOffset);
						uFieldFootprint = xField.m_uSize ? xField.m_uSize : 4;
					}
					else if (pxMap && xField.m_uArrayCount > 1)
					{
						// Array of mapped type — switch member prefix to `a`.
						snprintf(szField, sizeof(szField),
								 "\t\t\t%s m_a%s[%u]; // slang=%s offset=%u\n",
								 pxMap->m_szCpp,
								 strFieldIdent.c_str(),
								 xField.m_uArrayCount,
								 xField.m_strTypeName.c_str(),
								 xField.m_uOffset);
						// Slang reflection's m_uSize for an array is the
						// total stride * count, so it's the right footprint.
						uFieldFootprint = xField.m_uSize ? xField.m_uSize : 4 * xField.m_uArrayCount;
					}
					else
					{
						// Unknown type — emit a sized byte buffer so sizeof(_CB)
						// stays correct; the size_assert below still fires when
						// the reflected size drifts.
						const u_int uByteSize = xField.m_uSize ? xField.m_uSize : 4;
						snprintf(szField, sizeof(szField),
								 "\t\t\tunsigned char m_a%s[%u]; // slang=%s offset=%u arrayCount=%u (no C++ mapping)\n",
								 strFieldIdent.c_str(),
								 uByteSize,
								 xField.m_strTypeName.empty() ? "?" : xField.m_strTypeName.c_str(),
								 xField.m_uOffset,
								 xField.m_uArrayCount);
						uFieldFootprint = uByteSize;
					}
					strContent += szField;
					uRunningOffset = xField.m_uOffset + uFieldFootprint;
				}

				// Trailing std140 pad. m_uSize is the linked CB size from
				// reflection; if the last field doesn't reach it, std140 is
				// asking for trailing pad.
				if (xBinding.m_uSize > uRunningOffset)
				{
					const u_int uPad = xBinding.m_uSize - uRunningOffset;
					char szPad[160];
					snprintf(szPad, sizeof(szPad),
							 "\t\t\tunsigned char m_aPad_%u[%u];\n",
							 uRunningOffset, uPad);
					strContent += szPad;
				}

				strContent += "\t\t};\n";

				// Size + per-field offset asserts catch struct drift between
				// the GPU side (Slang) and host side (C++) at compile time.
				char szSizeAssert[256];
				snprintf(szSizeAssert, sizeof(szSizeAssert),
						 "\t\tstatic_assert(sizeof(%s_CB) == %u, \"%s_CB size drifted from Slang reflection\");\n",
						 strBindIdent.c_str(), xBinding.m_uSize, strBindIdent.c_str());
				strContent += szSizeAssert;

				for (u_int f = 0; f < xBinding.m_axFields.GetSize(); f++)
				{
					const Flux_ReflectedField& xField = xBinding.m_axFields.Get(f);
					std::string strFieldIdent = SanitizeIdentifier(xField.m_strName);
					const CppMapping* pxMap = MapSlangTypeToCpp(xField.m_strTypeName);
					if (!pxMap) continue; // byte-buffer fallback has no symbolic name to offsetof
					char szOffsetAssert[256];
					if (xField.m_uArrayCount <= 1)
					{
						snprintf(szOffsetAssert, sizeof(szOffsetAssert),
								 "\t\tstatic_assert(offsetof(%s_CB, m_%c%s) == %u, \"%s.%s offset drifted from Slang reflection\");\n",
								 strBindIdent.c_str(), pxMap->m_chHungarian, strFieldIdent.c_str(), xField.m_uOffset,
								 strBindIdent.c_str(), strFieldIdent.c_str());
					}
					else
					{
						snprintf(szOffsetAssert, sizeof(szOffsetAssert),
								 "\t\tstatic_assert(offsetof(%s_CB, m_a%s) == %u, \"%s.%s offset drifted from Slang reflection\");\n",
								 strBindIdent.c_str(), strFieldIdent.c_str(), xField.m_uOffset,
								 strBindIdent.c_str(), strFieldIdent.c_str());
					}
					strContent += szOffsetAssert;
				}
			}
		}

		strContent += "\t}\n\n";
	}

	strContent += "}\n";

	return strContent;
}

bool Flux_CodeGenerator::WriteSubsystemHeader(const char* szOutputDir,
											   const char* szSubsystem,
											   const ProgramReflection* axPrograms,
											   u_int uProgramCount)
{
	std::string strContent = BuildSubsystemHeaderContent(szSubsystem, axPrograms, uProgramCount);
	std::string strSubsystem = szSubsystem ? szSubsystem : "Misc";
	std::string strPath = std::string(szOutputDir) + strSubsystem + ".h";
	return WriteIfChanged(strPath, strContent);
}

bool Flux_CodeGenerator::WriteAllHeaders(const char* szOutputDir,
										  const ProgramReflection* axAll,
										  u_int uProgramCount)
{
	bool bOk = WriteProgramEnumHeader(szOutputDir);

	// Group programs by subsystem. std::map (sorted) instead of
	// std::unordered_map so that the order in which subsystem files are
	// touched on disk is also deterministic — the per-file contents were
	// already deterministic (registry iteration order is fixed) but unordered
	// iteration would still give different timestamps run-to-run when the
	// content matches and WriteIfChanged early-outs.
	std::map<std::string, std::vector<ProgramReflection>> xBySubsystem;
	for (u_int u = 0; u < uProgramCount; u++)
	{
		const ProgramReflection& xPR = axAll[u];
		if (xPR.m_eId >= FluxShaderProgram::COUNT) continue;
		const Flux_ShaderRegistryEntry& xEntry = Flux_ShaderRegistry::GetProgram(xPR.m_eId);
		std::string strSubsystem = xEntry.m_szSubsystem ? xEntry.m_szSubsystem : "Misc";
		xBySubsystem[strSubsystem].push_back(xPR);
	}

	for (const auto& xPair : xBySubsystem)
	{
		bOk = bOk && WriteSubsystemHeader(szOutputDir,
										   xPair.first.c_str(),
										   xPair.second.data(),
										   static_cast<u_int>(xPair.second.size()));
	}
	return bOk;
}
