#pragma once
// =====================================================================
// AUTO-GENERATED by Tools/dp_import/generate_level_data.py
// from Games/DevilsPlayground/Assets/Maps/DevilsPlayground_L_GameLevel.json
// DO NOT EDIT — regenerate after every asset re-export.
// =====================================================================

#include <cstdint>

namespace DP_LevelData
{
	struct LightInfo
	{
		float r, g, b;        // Linear-RGB 0..1 (UE 0..255 / 255)
		float intensity;     // UE intensity (we map to lumens 1:1 for skeleton)
	};

	struct Placement
	{
		float       x, y, z;     // Zenith (Z-forward, Y-up, metres)
		float       yaw;         // Y-axis rotation, radians
		const char* label;       // UE actor label, for debug
		const char* mesh;        // UE asset path; "" if no mesh in source
		LightInfo   light;       // {0,0,0,0} when actor has no light
		float       sx, sy, sz;  // UE scale (1,1,1 when omitted)
	};

	// 6 placements (Chest)
	static constexpr Placement kChest[] = {
		{ 35.1446f, 1.0000f, 37.2457f, -0.3491f, "BP_ChestInteractable", "/Engine/BasicShapes/Plane.Plane", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 25.6528f, 1.0000f, 13.0974f, -0.1745f, "BP_ChestInteractable2", "/Engine/BasicShapes/Plane.Plane", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 91.7554f, 1.0000f, 28.5042f, 0.3491f, "BP_ChestInteractable3", "/Engine/BasicShapes/Plane.Plane", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 70.9157f, 1.0000f, 38.7078f, -1.5708f, "BP_ChestInteractable4", "/Engine/BasicShapes/Plane.Plane", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 30.0103f, 1.0000f, 79.0756f, -1.5708f, "BP_ChestInteractable5", "/Engine/BasicShapes/Plane.Plane", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 61.5913f, 1.0000f, 94.1890f, 1.5708f, "BP_ChestInteractable6", "/Engine/BasicShapes/Plane.Plane", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kChestCount = sizeof(kChest) / sizeof(kChest[0]);

	// 1 placements (DirectionalLight)
	static constexpr Placement kDirectionalLight[] = {
		{ 0.0000f, 0.0000f, 0.0000f, 0.2967f, "DirectionalLight", "", { 0.2353f, 0.2157f, 0.4039f, 10.0000f }, 2.5000f, 2.5000f, 2.5000f },
	};
	static constexpr uint32_t kDirectionalLightCount = sizeof(kDirectionalLight) / sizeof(kDirectionalLight[0]);

	// 15 placements (Door)
	static constexpr Placement kDoor[] = {
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door15", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door6", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door7", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door8", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door9", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door11", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door13", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door14", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door19", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door20", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door16", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door4", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door17", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door5", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "BP_Door18", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kDoorCount = sizeof(kDoor) / sizeof(kDoor[0]);

	// 15 placements (ItemSpawn)
	static constexpr Placement kItemSpawn[] = {
		{ 9.0000f, 1.0000f, 39.1000f, 0.0000f, "BP_ItemSpawn", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 20.5000f, 1.0000f, 48.9000f, 0.0000f, "BP_ItemSpawn2", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 24.3000f, 1.0000f, 35.6000f, 0.0000f, "BP_ItemSpawn3", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 58.7000f, 1.0000f, 10.7000f, 0.0000f, "BP_ItemSpawn4", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 61.0000f, 1.0000f, 17.7000f, 0.0000f, "BP_ItemSpawn5", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 54.9000f, 1.0000f, 33.8000f, 0.0000f, "BP_ItemSpawn6", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 78.9000f, 1.0000f, 38.6000f, 0.0000f, "BP_ItemSpawn7", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 89.9000f, 1.0000f, 79.7000f, 0.0000f, "BP_ItemSpawn8", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 76.0000f, 1.0000f, 76.0000f, 0.0000f, "BP_ItemSpawn9", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 67.0000f, 1.0000f, 79.1000f, 0.0000f, "BP_ItemSpawn10", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 49.5000f, 1.0000f, 82.1000f, 0.0000f, "BP_ItemSpawn11", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 64.6000f, 1.0000f, 87.4000f, 0.0000f, "BP_ItemSpawn12", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 31.7000f, 1.0000f, 95.3000f, 0.0000f, "BP_ItemSpawn13", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 3.8000f, 1.0000f, 91.7000f, 0.0000f, "BP_ItemSpawn14", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 88.3000f, 1.0000f, 17.5000f, 0.0000f, "BP_ItemSpawn15", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kItemSpawnCount = sizeof(kItemSpawn) / sizeof(kItemSpawn[0]);

	// 24 placements (Light)
	static constexpr Placement kLight[] = {
		{ 63.6130f, 3.6421f, 71.1113f, -0.1745f, "BP_Light", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 44.5207f, 3.6421f, 81.2628f, -1.7453f, "BP_Light7", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 50.2671f, 3.4421f, 92.9101f, -1.5708f, "BP_Light8", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 36.4629f, 3.6421f, 36.7580f, 0.0000f, "BP_Light9", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 18.1532f, 3.6421f, 42.9321f, -1.7453f, "BP_Light10", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 21.1600f, 3.6421f, 82.2725f, 0.0000f, "BP_Light11", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 66.1260f, 3.6421f, 88.0857f, 1.5708f, "BP_Light20", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 38.9991f, 3.6421f, 23.1989f, -1.9199f, "BP_Light12", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 46.4883f, 3.6421f, 24.3735f, 2.7925f, "BP_Light13", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 61.8590f, 3.6421f, 13.2035f, -0.3491f, "BP_Light14", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 17.2404f, 3.6421f, 22.9130f, -2.6180f, "BP_Light15", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 17.9594f, 3.6421f, 10.2177f, -1.0472f, "BP_Light16", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 20.3742f, 3.6421f, 59.4553f, -1.5708f, "BP_Light17", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 29.1482f, 3.6421f, 66.7698f, -3.1416f, "BP_Light18", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 17.4776f, 3.6421f, 89.4138f, -1.5708f, "BP_Light19", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 47.7010f, 3.6421f, 75.3587f, 0.0000f, "BP_Light2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 53.7974f, 3.6421f, 47.5643f, 3.1416f, "BP_Light3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 45.2409f, 3.6421f, 47.5685f, 3.1416f, "BP_Light4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 28.3327f, 3.6421f, 49.2579f, 2.9671f, "BP_Light5", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 63.2722f, 3.6421f, 41.9505f, -1.5708f, "BP_Light6", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 71.2722f, 2.8821f, 54.6905f, -1.5708f, "BP_Light21", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 76.5522f, 2.8821f, 60.7205f, -3.1416f, "BP_Light22", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 79.1342f, 2.7900f, 17.1280f, -1.9199f, "BP_Light23", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 77.2481f, 2.8821f, 73.0795f, -0.8727f, "BP_Light24", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 1.0000f, 0.9059f, 0.5686f, 1000.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kLightCount = sizeof(kLight) / sizeof(kLight[0]);

	// 21 placements (MushroomGroup)
	static constexpr Placement kMushroomGroup[] = {
		{ 73.5000f, 1.0000f, 18.6500f, 0.0000f, "BP_MushroomGroup", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 3.2500f, 3.2500f },
		{ 73.2192f, 1.0000f, 18.9261f, -2.9671f, "BP_MushroomGroup2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 74.1753f, 1.0000f, 17.6762f, -1.2217f, "BP_MushroomGroup3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 2.0000f, 2.0000f, 2.0000f },
		{ 73.7200f, 1.0000f, 17.8300f, 0.0000f, "BP_MushroomGroup4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 75.3383f, 1.0000f, 20.4793f, -1.3963f, "BP_MushroomGroup5", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 75.7900f, 1.0000f, 20.2600f, 0.0000f, "BP_MushroomGroup6", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.7500f, 1.7500f, 1.7500f },
		{ 83.0755f, 1.0000f, 30.9052f, -1.0472f, "BP_MushroomGroup7", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 4.7500f, 4.7500f, 4.7500f },
		{ 82.5900f, 1.0000f, 29.8900f, -1.5708f, "BP_MushroomGroup8", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 82.5112f, 1.0000f, 30.7902f, 1.7453f, "BP_MushroomGroup9", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 83.3456f, 1.0000f, 31.6508f, -2.0944f, "BP_MushroomGroup10", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 83.8565f, 1.5290f, 30.2773f, -0.3491f, "BP_MushroomGroup11", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 84.1063f, 1.9400f, 30.7666f, -1.9199f, "BP_MushroomGroup12", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.5000f, 1.5000f, 1.5000f },
		{ 84.2773f, 1.6000f, 31.2364f, -0.3491f, "BP_MushroomGroup13", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 79.3200f, 1.0000f, 7.0600f, -1.5708f, "BP_MushroomGroup14", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 8.2500f, 8.2500f, 8.2500f },
		{ 77.6155f, 1.0000f, 7.9763f, 0.6981f, "BP_MushroomGroup15", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 4.2500f, 4.2500f, 4.2500f },
		{ 87.7600f, 1.0000f, 33.3300f, 0.0000f, "BP_MushroomGroup16", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 3.2500f, 3.2500f },
		{ 91.9706f, 1.0000f, 32.3057f, -0.6981f, "BP_MushroomGroup17", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 7.5000f, 6.5000f, 7.5000f },
		{ 80.8500f, 1.0000f, 23.9400f, 2.9671f, "BP_MushroomGroup18", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 80.9300f, 1.0000f, 25.9200f, -0.8727f, "BP_MushroomGroup19", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 80.0400f, 1.0000f, 24.6900f, 0.0000f, "BP_MushroomGroup20", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 81.3331f, 1.0000f, 24.7647f, -1.9199f, "BP_MushroomGroup21", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kMushroomGroupCount = sizeof(kMushroomGroup) / sizeof(kMushroomGroup[0]);

	// 1 placements (Niagara)
	static constexpr Placement kNiagara[] = {
		{ 85.8263f, 2.0000f, 25.7546f, 1.2217f, "PFX_Witch", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kNiagaraCount = sizeof(kNiagara) / sizeof(kNiagara[0]);

	// 1 placements (PlayerStart)
	static constexpr Placement kPlayerStart[] = {
		{ 20.8824f, 16.2092f, 65.6091f, 0.0000f, "PlayerStart", "", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kPlayerStartCount = sizeof(kPlayerStart) / sizeof(kPlayerStart[0]);

	// 1 placements (PointLight)
	static constexpr Placement kPointLight[] = {
		{ 88.0019f, 1.7800f, 25.1225f, -0.0000f, "PointLight2", "", { 0.0000f, 1.0000f, 0.0000f, 35.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kPointLightCount = sizeof(kPointLight) / sizeof(kPointLight[0]);

	// 1 placements (Priest)
	static constexpr Placement kPriest[] = {
		{ 62.4000f, 1.0000f, 56.5000f, 0.0000f, "BP_PriestPawn", "/Game/DevilsPlayground/Assets/Characters/Pope/SM_Pope.SM_Pope", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kPriestCount = sizeof(kPriest) / sizeof(kPriest[0]);

	// 139 placements (StaticDeco)
	static constexpr Placement kStaticDeco[] = {
		{ 0.0000f, 0.0000f, 0.0000f, 0.0000f, "SM_Floor", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 100.0000f, 1.0000f, 100.0000f },
		{ 100.0000f, 1.0000f, 0.0000f, 1.5708f, "SM_Cube4", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 5.0000f, 100.0000f },
		{ 100.0000f, 1.0000f, 99.0000f, 1.5708f, "SM_Cube6", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 5.0000f, 100.0000f },
		{ 100.0000f, 1.0000f, 100.0000f, 3.1416f, "SM_Cube7", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 5.0000f, 100.0000f },
		{ 1.0000f, 1.0000f, 100.0000f, 3.1416f, "SM_Cube9", "/Game/LevelPrototyping/Meshes/SM_Cube.SM_Cube", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 5.0000f, 100.0000f },
		{ 67.6666f, 1.0000f, 52.3764f, -0.3491f, "SM_Forge", "/Game/DevilsPlayground/Assets/Blockout/Blacksmith/Forge.Forge", { 1.0000f, 0.6745f, 0.0941f, 35.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 72.0000f, 1.0000f, 60.0000f, -1.5708f, "CornerWallSection", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 76.0000f, 1.0000f, 60.0000f, 3.1416f, "WallSection2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 1.0000f, 1.0000f },
		{ 80.0000f, 1.0000f, 60.0000f, -3.1416f, "CornerWallSection2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 80.0000f, 1.0000f, 49.0000f, 1.5708f, "WallSection9", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 10.0000f, 1.0000f, 1.0000f },
		{ 80.0000f, 1.0000f, 38.0000f, 1.5708f, "CornerSection3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 72.0000f, 1.0000f, 38.0000f, 0.0000f, "WallSection18", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 7.0000f, 1.0000f, 1.0000f },
		{ 64.0000f, 1.0000f, 38.0000f, 0.0000f, "CornerSection4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 64.0000f, 1.0000f, 42.0000f, -1.5708f, "WallSection23", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 1.0000f, 1.0000f },
		{ 64.0000f, 1.0000f, 46.0000f, -1.5708f, "CornerSection5", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 68.0000f, 1.0000f, 46.0000f, -3.1416f, "WallSection26", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 1.0000f, 1.0000f },
		{ 72.0000f, 1.0000f, 52.0000f, -1.5708f, "WallSection29", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 5.0000f, 1.0000f, 1.0000f },
		{ 72.0000f, 1.0000f, 46.0000f, 3.1416f, "InnerWallSection", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/InnerWallSection.InnerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 35.0054f, 1.0000f, 58.0392f, 1.5708f, "CornerSection1", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 35.0054f, 1.0000f, 66.0392f, -3.1416f, "CornerSection2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 35.0054f, 1.0000f, 61.0392f, 1.5708f, "WallSection1", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 2.0000f, 1.0000f, 1.0000f },
		{ 28.1054f, 1.0000f, 66.0392f, -3.1416f, "WallSection2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.0000f, 1.0000f, 1.0000f },
		{ 21.1054f, 1.0000f, 66.0392f, -1.5708f, "CornerSection3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 21.1054f, 1.0000f, 62.0392f, -1.5708f, "WallSection3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 1.0000f, 1.0000f },
		{ 21.1054f, 1.0000f, 58.0392f, 0.0000f, "CornerSection4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 28.0054f, 1.0000f, 58.0392f, 0.0000f, "WallSection4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.0000f, 1.0000f, 1.0000f },
		{ 56.0054f, 1.0000f, 46.8392f, -3.1416f, "CornerSection1", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 43.0054f, 1.0000f, 46.8392f, -1.5708f, "CornerSection2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 43.0054f, 1.0000f, 32.9392f, 0.0000f, "CornerSection3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 56.0054f, 1.0000f, 32.9392f, 1.5708f, "CornerSection4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 52.0054f, 1.0000f, 46.8392f, -3.1416f, "WallSection1", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 1.0000f, 1.0000f },
		{ 43.0054f, 1.0000f, 39.8392f, -1.5708f, "WallSection2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.0000f, 1.0000f, 1.0000f },
		{ 49.5054f, 1.0000f, 32.9392f, 0.0000f, "WallSection3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 5.5000f, 1.0000f, 1.0000f },
		{ 56.0054f, 1.0000f, 39.8392f, 1.5708f, "WallSection4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.0000f, 1.0000f, 1.0000f },
		{ 45.5054f, 1.0000f, 46.8392f, -3.1416f, "WallSection5", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.5000f, 1.0000f, 1.0000f },
		{ 44.1929f, 1.0000f, 75.2803f, -0.1745f, "CornerSection6", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 66.8435f, 1.0000f, 71.2864f, 1.3963f, "CornerSection7", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 68.3195f, 1.0000f, 79.6573f, 2.9671f, "CornerSection8", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 45.6689f, 1.0000f, 83.6512f, -1.7453f, "CornerSection9", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 56.5030f, 1.0000f, 73.1097f, -0.1745f, "WallSection6", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 9.5000f, 1.0000f, 1.0000f },
		{ 67.5728f, 1.0000f, 75.4226f, 1.3963f, "WallSection7", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.5000f, 1.0000f, 1.0000f },
		{ 56.9942f, 1.0000f, 81.6542f, 2.9671f, "WallSection8", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 10.5000f, 1.0000f, 1.0000f },
		{ 44.9483f, 1.0000f, 79.5642f, -1.7453f, "WallSection10", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.5000f, 1.0000f, 1.0000f },
		{ 26.3828f, 1.0000f, 34.7528f, -0.1745f, "WallSection11", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 8.0000f, 1.0000f, 1.0000f },
		{ 32.4639f, 1.0000f, 45.0534f, 1.3963f, "WallSection12", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 2.0000f, 1.0000f, 1.0000f },
		{ 35.2461f, 1.0000f, 33.1900f, 1.3963f, "CornerSection10", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 32.9327f, 1.0000f, 47.7124f, 2.9671f, "CornerSection11", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 27.0239f, 1.0000f, 48.7542f, 2.9671f, "WallSection13", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 1.0000f, 1.0000f },
		{ 22.5923f, 1.0000f, 49.5357f, 2.9671f, "WallSection14", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.5000f, 1.0000f, 1.0000f },
		{ 17.7165f, 1.0000f, 36.2810f, -0.1745f, "CornerSection12", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 18.9147f, 1.0000f, 43.0761f, -1.7453f, "WallSection15", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.0000f, 1.0000f, 1.0000f },
		{ 20.1302f, 1.0000f, 49.9698f, -1.7453f, "CornerSection13", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 36.6700f, 1.0000f, 41.2654f, 2.9671f, "CornerSection14", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 31.9429f, 1.0000f, 42.0989f, 1.3963f, "InnerWallSection2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/InnerWallSection.InnerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 34.6019f, 1.0000f, 41.6301f, 2.9671f, "WallSection16", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.7500f, 1.0000f, 1.0000f },
		{ 35.9754f, 1.0000f, 37.3262f, 1.3963f, "WallSection17", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 1.0000f, 1.0000f },
		{ 51.0000f, 1.0000f, 88.5000f, -1.5708f, "WallSection", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.5000f, 1.0000f, 1.0000f },
		{ 51.0000f, 1.0000f, 86.0000f, 0.0000f, "CornerWallSection3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 58.2000f, 1.0000f, 86.0000f, 0.0000f, "WallSection19", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.2500f, 1.0000f, 1.0000f },
		{ 65.4000f, 1.0000f, 86.0000f, 1.5708f, "CornerWallSection4", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 65.4000f, 1.0000f, 90.5000f, 1.5708f, "WallSection20", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.5000f, 1.0000f, 1.0000f },
		{ 65.4000f, 1.0000f, 95.0000f, 3.1416f, "CornerWallSection5", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 58.2500f, 1.0000f, 95.0000f, 3.1416f, "WallSection21", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.2500f, 1.0000f, 1.0000f },
		{ 51.0000f, 1.0000f, 95.0000f, -1.5708f, "CornerWallSection6", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 51.0000f, 1.0000f, 93.0000f, -1.5708f, "WallSection22", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 25.2000f, 1.0000f, 78.0000f, 0.0000f, "CornerWallSection7", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 25.2000f, 1.0000f, 79.5000f, -1.5708f, "WallSection24", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 0.5000f, 1.0000f, 1.0000f },
		{ 25.2000f, 1.0000f, 83.0000f, -1.5708f, "InnerWallSection3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/InnerWallSection.InnerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 21.7000f, 1.0000f, 83.0000f, 0.0000f, "WallSection25", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 2.5000f, 1.0000f, 1.0000f },
		{ 18.2000f, 1.0000f, 83.0000f, 0.0000f, "CornerWallSection8", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 18.2000f, 1.0000f, 89.8000f, -1.5708f, "WallSection27", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 5.7500f, 1.0000f, 1.0000f },
		{ 18.2000f, 1.0000f, 96.5000f, -1.5708f, "CornerWallSection9", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 26.7000f, 1.0000f, 96.5000f, 3.1416f, "WallSection28", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 7.5000f, 1.0000f, 1.0000f },
		{ 35.2000f, 1.0000f, 96.5000f, -3.1416f, "CornerWallSection10", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 35.2000f, 1.0000f, 87.2000f, 1.5708f, "WallSection30", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 8.5000f, 1.0000f, 1.0000f },
		{ 35.2000f, 1.0000f, 78.0000f, 1.5708f, "CornerWallSection11", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 30.4000f, 1.0000f, 78.0000f, 0.0000f, "WallSection31", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 4.2500f, 1.0000f, 1.0000f },
		{ 11.1000f, 1.0000f, 85.0000f, 1.5708f, "WallSection32", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.7500f, 1.0000f, 1.0000f },
		{ 11.1000f, 1.0000f, 92.7000f, 3.1416f, "CornerWallSection12", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 7.4000f, 1.0000f, 92.7000f, 3.1416f, "WallSection34", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 2.7500f, 1.0000f, 1.0000f },
		{ 3.7000f, 1.0000f, 92.7000f, -1.5708f, "CornerWallSection13", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 3.7000f, 1.0000f, 85.0000f, -1.5708f, "WallSection33", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.7500f, 1.0000f, 1.0000f },
		{ 11.1000f, 1.0000f, 77.4000f, 1.5708f, "CornerWallSection14", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 3.7000f, 1.0000f, 77.4000f, -0.0000f, "CornerWallSection15", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 6.4000f, 1.0000f, 77.4000f, 0.0000f, "WallSection35", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.7500f, 1.0000f, 1.0000f },
		{ 11.8000f, 1.0000f, 38.2000f, 1.5708f, "CornerWallSection16", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 11.8000f, 1.0000f, 43.3500f, 1.5708f, "WallSection36", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 4.2500f, 1.0000f, 1.0000f },
		{ 11.8131f, 1.0000f, 50.5926f, 3.1416f, "CornerWallSection17", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 9.1000f, 1.0000f, 50.6000f, 3.1416f, "WallSection37", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.7500f, 1.0000f, 1.0000f },
		{ 6.4131f, 1.0000f, 50.5926f, -1.5708f, "CornerWallSection18", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 6.4000f, 1.0000f, 38.2000f, -0.0000f, "CornerWallSection19", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 9.1000f, 1.0000f, 38.2000f, 0.0000f, "WallSection38", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.7500f, 1.0000f, 1.0000f },
		{ 6.4000f, 1.0000f, 44.4000f, -1.5708f, "WallSection39", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 5.2500f, 1.0000f, 1.0000f },
		{ 20.5000f, 1.0000f, 23.9622f, -2.6180f, "CornerWallSection20", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 16.8194f, 1.0000f, 21.8372f, -2.6180f, "WallSection40", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 1.0000f, 1.0000f },
		{ 13.2687f, 1.0000f, 19.7872f, -1.0472f, "CornerWallSection21", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 16.5187f, 1.0000f, 14.1580f, -1.0472f, "WallSection41", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 5.5000f, 1.0000f, 1.0000f },
		{ 19.7687f, 1.0000f, 8.5288f, 0.5236f, "CornerWallSection22", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 23.3627f, 1.0000f, 10.6038f, 0.5236f, "WallSection42", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 1.0000f, 1.0000f },
		{ 27.0000f, 1.0000f, 12.7038f, 2.0944f, "CornerWallSection23", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 24.2500f, 1.0000f, 17.4670f, 2.0944f, "WallSection43", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 4.5000f, 1.0000f, 1.0000f },
		{ 51.5401f, 1.0000f, 21.7731f, 2.7925f, "WallSection44", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 10.7500f, 1.0000f, 1.0000f },
		{ 62.4405f, 1.0000f, 17.8057f, 2.7925f, "CornerWallSection24", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 61.0040f, 1.0000f, 13.8590f, 1.2217f, "WallSection45", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 1.0000f, 1.0000f },
		{ 59.5847f, 1.0000f, 9.9593f, 1.2217f, "CornerWallSection25", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 48.6842f, 1.0000f, 13.9267f, -0.3491f, "WallSection46", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 10.7500f, 1.0000f, 1.0000f },
		{ 37.8308f, 1.0000f, 17.8770f, -0.3491f, "CornerWallSection26", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 38.4293f, 1.0000f, 19.5215f, -1.9199f, "WallSection47", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 0.7500f, 1.0000f, 1.0000f },
		{ 40.6866f, 1.0000f, 25.7235f, -1.9199f, "CornerWallSection27", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 39.9000f, 1.0000f, 23.5622f, -1.9199f, "WallSection48", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.5000f, 1.0000f, 1.0000f },
		{ 89.2559f, 1.0000f, 18.3819f, 1.2217f, "WallSection49", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 10.7500f, 1.0000f, 1.0000f },
		{ 85.2372f, 1.0000f, 7.3405f, 1.2217f, "CornerWallSection28", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 81.2905f, 1.0000f, 8.7770f, -0.3491f, "WallSection50", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 1.0000f, 1.0000f },
		{ 80.4689f, 1.0000f, 18.6536f, -1.9199f, "WallSection51", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 8.0000f, 1.0000f, 1.0000f },
		{ 77.3907f, 1.0000f, 10.1964f, -0.3491f, "CornerWallSection29", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 84.4877f, 1.0000f, 29.6950f, -1.9199f, "WallSection54", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.7500f, 1.0000f, 1.0000f },
		{ 93.2746f, 1.0000f, 29.4233f, 2.7925f, "CornerWallSection30", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 89.3749f, 1.0000f, 30.8427f, 2.7925f, "WallSection52", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.2500f, 1.0000f, 1.0000f },
		{ 85.4282f, 1.0000f, 32.2792f, -1.9199f, "CornerWallSection31", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 93.0753f, 1.0000f, 76.9733f, 2.2689f, "CornerSection15", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 88.8972f, 1.0000f, 81.9526f, 2.2689f, "WallSection53", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 5.5000f, 1.0000f, 1.0000f },
		{ 84.7191f, 1.0000f, 86.9319f, -2.4435f, "CornerSection16", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 79.4334f, 1.0000f, 82.4967f, -2.4435f, "WallSection55", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.0000f, 1.0000f, 1.0000f },
		{ 74.0711f, 1.0000f, 77.9971f, -0.8727f, "CornerSection17", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 76.6422f, 1.0000f, 74.9330f, -0.8727f, "WallSection56", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 1.0000f, 1.0000f },
		{ 80.8204f, 1.0000f, 69.9537f, -0.8727f, "WallSection57", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.5000f, 1.0000f, 1.0000f },
		{ 87.7896f, 1.0000f, 72.5381f, 0.6981f, "WallSection58", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/WallSection.WallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.0000f, 1.0000f, 1.0000f },
		{ 82.4273f, 1.0000f, 68.0386f, 0.6981f, "CornerSection18", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/CornerWallSection.CornerWallSection", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 66.2190f, 1.0000f, 55.5017f, -1.2217f, "SM_Anvil", "/Game/DevilsPlayground/Assets/Blockout/Blacksmith/Anvil.Anvil", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 47.6086f, 1.0000f, 61.5825f, -0.8727f, "Well", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Well.Well", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 87.9864f, 1.0000f, 25.1175f, -1.2217f, "Cauldron", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Cauldron.Cauldron", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 75.0961f, 1.0000f, 18.9958f, 0.6981f, "Well2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Well.Well", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 82.2300f, 1.0000f, 5.7900f, 0.0000f, "RedMushroom", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 24.1811f, 37.0000f, 24.1811f },
		{ 89.3600f, 1.0000f, 33.2800f, -0.6981f, "GreenMushroom", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/GreenMushroom.GreenMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 17.2500f, 17.2500f, 17.2500f },
		{ 91.0000f, 1.0000f, 33.4900f, -1.2217f, "GreenMushroom2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/GreenMushroom.GreenMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.7500f, 6.7500f, 6.7500f },
		{ 90.4133f, 1.0000f, 34.6132f, -0.8727f, "BrownMushroom", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/BrownMushroom.BrownMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 6.2500f, 6.2500f, 6.2500f },
		{ 81.5200f, 1.0000f, 25.5800f, 1.5708f, "BrownMushroom2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/BrownMushroom.BrownMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 8.0000f, 8.0000f, 8.0000f },
		{ 80.6500f, 1.0000f, 24.7100f, -0.5236f, "GreenMushroom3", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/GreenMushroom.GreenMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 5.2500f, 5.2500f, 5.2500f },
		{ 80.7500f, 1.0000f, 25.3600f, 1.7453f, "RedMushroom2", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/RedMushroom.RedMushroom", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 3.0000f, 3.0000f, 3.0000f },
	};
	static constexpr uint32_t kStaticDecoCount = sizeof(kStaticDeco) / sizeof(kStaticDeco[0]);

	// 17 placements (Villager)
	static constexpr Placement kVillager[] = {
		{ 25.7000f, 1.8800f, 27.0000f, 0.0000f, "BP_Pleb", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 56.9000f, 1.8800f, 64.9000f, 0.0000f, "BP_Pleb6", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 62.4000f, 1.8800f, 25.1000f, 0.0000f, "BP_Pleb7", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 71.9000f, 1.8800f, 28.7000f, 0.0000f, "BP_Pleb8", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 90.7000f, 1.8800f, 49.3000f, 0.0000f, "BP_Pleb9", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 91.4000f, 1.8800f, 66.7000f, 0.0000f, "BP_Pleb10", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 37.1000f, 1.8800f, 11.4000f, 0.0000f, "BP_Pleb11", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 5.8000f, 1.8800f, 21.6000f, 0.0000f, "BP_Pleb12", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 78.3000f, 1.8800f, 92.0000f, 0.0000f, "BP_Pleb13", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 90.1000f, 1.8800f, 40.4000f, 0.0000f, "BP_Pleb14", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 6.5000f, 1.8800f, 60.5000f, 0.0000f, "BP_Pleb2", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 38.3000f, 1.8800f, 53.8000f, 0.0000f, "BP_Pleb3", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 45.1000f, 1.8800f, 66.9000f, 0.0000f, "BP_Pleb4", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 40.9000f, 1.8800f, 91.2000f, 0.0000f, "BP_Pleb5", "/Game/DevilsPlayground/Assets/Characters/Peasent/SM_Peasant.SM_Peasant", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 65.2000f, 1.8800f, 53.1000f, 0.0000f, "BP_Blacksmith", "/Game/DevilsPlayground/Assets/Characters/Blacksmith/SM_Blacksmith.SM_Blacksmith", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 67.9000f, 1.8800f, 55.7000f, 0.0000f, "BP_Blacksmith2", "/Game/DevilsPlayground/Assets/Characters/Blacksmith/SM_Blacksmith.SM_Blacksmith", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
		{ 44.9000f, 1.8800f, 53.8000f, 0.0000f, "BP_Seer", "/Game/DevilsPlayground/Assets/Blockout/BuildingAssetKit/Torch.Torch", { 0.0000f, 0.0000f, 0.0000f, 0.0000f }, 1.0000f, 1.0000f, 1.0000f },
	};
	static constexpr uint32_t kVillagerCount = sizeof(kVillager) / sizeof(kVillager[0]);

} // namespace DP_LevelData
