#pragma once

// Engine-wide configuration constants are now in ZenithConfig.h
// This file includes them for backward compatibility with existing code
#include "Core/ZenithConfig.h"

enum CommandType
{
	COMMANDTYPE_GRAPHICS,
	COMMANDTYPE_COMPUTE,
	COMMANDTYPE_COPY,
	COMMANDTYPE_PRESENT,
	COMMANDTYPE_MAX
};

enum AllocationType
{
	ALLOCATION_TYPE_BUFFER,
	ALLOCATION_TYPE_TEXTURE,
	ALLOCATION_TYPE_COUNT,
};

enum TextureType
{
	TEXTURE_TYPE_2D,
	TEXTURE_TYPE_3D,
	TEXTURE_TYPE_CUBE
};

enum RenderOrder
{
	RENDER_ORDER_MEMORY_UPDATE,
	RENDER_ORDER_PROBE_CONVOLUTION,   // IBL probe irradiance/prefilter convolution
	RENDER_ORDER_CSM,
	RENDER_ORDER_ATMOSPHERE_LUT,      // Precompute transmittance LUT (compute)
	RENDER_ORDER_SKYBOX,              // Cubemap or procedural atmosphere
	RENDER_ORDER_OPAQUE_MESHES,
	RENDER_ORDER_TERRAIN_CULLING,
	RENDER_ORDER_TERRAIN,
	RENDER_ORDER_PRIMITIVES,  // Debug primitives - rendered after terrain, into GBuffer
	RENDER_ORDER_SKINNED_MESHES,
	RENDER_ORDER_INSTANCE_CULLING,  // GPU frustum culling compute pass for instanced meshes
	RENDER_ORDER_INSTANCED_MESHES,  // GPU-instanced meshes (100k+ instances)
	RENDER_ORDER_FOLIAGE,
	RENDER_ORDER_HIZ_GENERATE,        // Hi-Z depth pyramid (compute)
	RENDER_ORDER_SSR_RAYMARCH,        // Screen-space reflection ray marching
	RENDER_ORDER_SSGI_RAYMARCH,       // Screen-space GI ray marching
	RENDER_ORDER_SSR_RESOLVE,         // SSR roughness blur pass
	RENDER_ORDER_SSGI_UPSAMPLE,       // SSGI bilateral upsample to full res
	RENDER_ORDER_SSGI_DENOISE,        // SSGI joint bilateral denoising
	RENDER_ORDER_APPLY_LIGHTING,
	RENDER_ORDER_POINT_LIGHTS,
	RENDER_ORDER_WATER,
	RENDER_ORDER_SSAO,
	RENDER_ORDER_VOLUMEFOG_INJECT,    // Volumetric fog density injection (compute)
	RENDER_ORDER_VOLUMEFOG_LIGHT,     // Volumetric fog lighting pass (compute)
	RENDER_ORDER_VOLUMEFOG_TEMPORAL,  // Volumetric fog temporal resolve (compute)
	RENDER_ORDER_FOG,
	RENDER_ORDER_AERIAL_PERSPECTIVE,  // Atmospheric distance fog (after regular fog)
	RENDER_ORDER_SDFS,
	RENDER_ORDER_PARTICLES_COMPUTE,
	RENDER_ORDER_PARTICLES,
	RENDER_ORDER_HDR_LUMINANCE,       // Auto-exposure histogram (must be after all HDR scene rendering)
	RENDER_ORDER_HDR_ADAPTATION,      // Auto-exposure adaptation
	RENDER_ORDER_HDR_BLOOM_THRESHOLD, // Bloom threshold extraction (HDR scene -> bloom[0])
	RENDER_ORDER_HDR_BLOOM_DOWNSAMPLE,// Bloom downsample chain (bloom[i-1] -> bloom[i])
	RENDER_ORDER_HDR_BLOOM_UPSAMPLE,  // Bloom upsample chain (bloom[i+1] -> bloom[i], additive)
	RENDER_ORDER_HDR_TONEMAP,         // Tone mapping (reads HDR target, writes to final target)
	RENDER_ORDER_QUADS,               // UI quads (rendered on top of tone-mapped scene)
	RENDER_ORDER_TEXT,                // UI text (rendered on top of quads)
	RENDER_ORDER_COMPUTE_TEST,
	RENDER_ORDER_IMGUI,
	RENDER_ORDER_COPYTOFRAMEBUFFER,
	RENDER_ORDER_MAX
};

enum TextureFormat
{
	TEXTURE_FORMAT_NONE,

	TEXTURE_FORMAT_COLOUR_BEGIN,//////////////////////
	TEXTURE_FORMAT_RGB8_UNORM,
	TEXTURE_FORMAT_RGBA8_UNORM,
	TEXTURE_FORMAT_BGRA8_SRGB,
	TEXTURE_FORMAT_R16G16B16A16_UNORM,
	TEXTURE_FORMAT_BGRA8_UNORM,
	TEXTURE_FORMAT_R16G16B16A16_SFLOAT,
	TEXTURE_FORMAT_R32G32B32A32_SFLOAT,
	TEXTURE_FORMAT_R32G32B32_SFLOAT,
	TEXTURE_FORMAT_R32G32_SFLOAT,         // 64-bit RG float (for HiZ min-max depth)
	// BC Compressed formats
	TEXTURE_FORMAT_BC1_RGB_UNORM,      // 4 bits/pixel, RGB, no alpha (6:1 compression)
	TEXTURE_FORMAT_BC1_RGBA_UNORM,     // 4 bits/pixel, RGB + 1-bit alpha (6:1 compression)
	TEXTURE_FORMAT_BC3_RGBA_UNORM,     // 8 bits/pixel, RGB + smooth alpha (4:1 compression)
	TEXTURE_FORMAT_BC5_RG_UNORM,       // 8 bits/pixel, RG only, ideal for normal maps (4:1 compression)
	TEXTURE_FORMAT_BC7_RGBA_UNORM,     // 8 bits/pixel, high quality RGBA (4:1 compression)
	// Single-channel formats (for heightmaps) - added at end for backwards compatibility
	TEXTURE_FORMAT_R16_UNORM,          // 16-bit unsigned normalized
	TEXTURE_FORMAT_R32_SFLOAT,         // 32-bit float
	TEXTURE_FORMAT_R16G16_SFLOAT,      // 32-bit RG float (for BRDF LUT, etc.)
	TEXTURE_FORMAT_COLOUR_END,/////////////////////////

	TEXTURE_FORMAT_DEPTH_STENCIL_BEGIN,////////////////
	TEXTURE_FORMAT_D32_SFLOAT,
	TEXTURE_FORMAT_DEPTH_STENCIL_END,//////////////////
};

enum BlendFactor
{
	BLEND_FACTOR_DISABLED,
	BLEND_FACTOR_ZERO,
	BLEND_FACTOR_SRCALPHA,
	BLEND_FACTOR_ONEMINUSSRCALPHA,
	BLEND_FACTOR_ONE
};

enum DepthCompareFunc
{
	DEPTH_COMPARE_FUNC_DISABLED,
	DEPTH_COMPARE_FUNC_LESSEQUAL,
	DEPTH_COMPARE_FUNC_GREATEREQUAL,
	DEPTH_COMPARE_FUNC_NEVER,
	DEPTH_COMPARE_FUNC_ALWAYS
};

enum MeshTopology
{
	MESH_TOPOLOGY_NONE,
	MESH_TOPOLOGY_TRIANGLES,
	MESH_TOPOLOGY_TRIANGLESTRIPS,
};

enum ShaderDataType
{
	SHADER_DATA_TYPE_FLOAT,
	SHADER_DATA_TYPE_FLOAT2,
	SHADER_DATA_TYPE_FLOAT3,
	SHADER_DATA_TYPE_FLOAT4,
	SHADER_DATA_TYPE_INT,
	SHADER_DATA_TYPE_INT2,
	SHADER_DATA_TYPE_INT3,
	SHADER_DATA_TYPE_INT4,
	SHADER_DATA_TYPE_UINT,
	SHADER_DATA_TYPE_UINT2,
	SHADER_DATA_TYPE_UINT3,
	SHADER_DATA_TYPE_UINT4,
	SHADER_DATA_TYPE_MAT3,
	SHADER_DATA_TYPE_MAT4,
	SHADER_DATA_TYPE_BOOL,
	SHADER_DATA_TYPE_NONE
};

enum DescriptorType
{
	DESCRIPTOR_TYPE_BUFFER,
	DESCRIPTOR_TYPE_STORAGE_BUFFER,
	DESCRIPTOR_TYPE_TEXTURE,
	DESCRIPTOR_TYPE_STORAGE_IMAGE,
	DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE,
	DESCRIPTOR_TYPE_UNBOUNDED_TEXTURES,
	DESCRIPTOR_TYPE_MAX
};

enum LoadAction
{
	LOAD_ACTION_DONTCARE,
	LOAD_ACTION_LOAD,
	LOAD_ACTION_CLEAR
};

enum StoreAction
{
	STORE_ACTION_DONTCARE,
	STORE_ACTION_STORE,
};

enum RenderTargetUsage
{
	RENDER_TARGET_USAGE_RENDERTARGET,
	RENDER_TARGET_USAGE_SHADERREAD,
	RENDER_TARGET_USAGE_PRESENT
};

enum MemoryResidency
{
	MEMORY_RESIDENCY_CPU,
	MEMORY_RESIDENCY_GPU
};

enum BufferUsage
{
	BUFFER_USAGE_VERTEXBUFFER,
	BUFFER_USAGE_INDEXBUFFER
};

enum MRTIndex
{
	MRT_INDEX_DIFFUSE,
	MRT_INDEX_NORMALSAMBIENT,
	MRT_INDEX_MATERIAL,
	MRT_INDEX_COUNT,
};

enum MemoryFlags : u_int
{
	MEMORY_FLAGS__NONE = 0,
	MEMORY_FLAGS__SHADER_READ,
	MEMORY_FLAGS__UNORDERED_ACCESS,
	MEMORY_FLAGS__VERTEX_BUFFER,
	MEMORY_FLAGS__INDEX_BUFFER,
	MEMORY_FLAGS__INDIRECT_BUFFER,
};
