#pragma once

#define MAX_FRAMES_IN_FLIGHT 4

enum CommandType {
	COMMANDTYPE_GRAPHICS,
	COMMANDTYPE_COMPUTE,
	COMMANDTYPE_COPY,
	COMMANDTYPE_PRESENT,
	COMMANDTYPE_MAX
};

enum AllocationType {
	ALLOCATION_TYPE_BUFFER,
	ALLOCATION_TYPE_TEXTURE,
};

enum RenderOrder {
	RENDER_ORDER_MEMORY_UPDATE,
	RENDER_ORDER_SKYBOX,
	RENDER_ORDER_OPAQUE_MESHES,
	RENDER_ORDER_TERRAIN,
	RENDER_ORDER_SKINNED_MESHES,
	RENDER_ORDER_FOLIAGE,
#ifdef VCE_DEFERRED_SHADING
	RENDER_ORDER_APPLY_LIGHTING,
	RENDER_ORDER_POINT_LIGHTS,
#endif
	RENDER_ORDER_COPY_TO_FRAMEBUFFER,
	RENDER_ORDER_MAX
};

enum BindingFrequency {
	BINDING_FREQUENCY_PER_FRAME,
	BINDING_FREQUENCY_PER_DRAW,
	BINDING_FREQUENCY_MAX,
};

enum TextureFormat
{
	TEXTURE_FORMAT_RGBA,
	TEXTURE_FORMAT_RGB,
	TEXTURE_FORMAT_D
};